Benjamin-Lee/deep-rules

README.md
contributors.md

Add contributor list

---

.github/ISSUE_TEMPLATE/rule-proposal.md

Add a checkbox for the contributor list.  @Benjamin-Lee you can rephrase this if you want, but it might save you some time instead instead of having to ask individually.

Update issue template

---

CONTRIBUTING.md
README.md

Adds information about the current status of the project (we are no longer actively soliciting new rules as much as combining the rules we already have) to the README as well as clarifies when to PR vs commit.
Can someone with experience from the deep review make sure that the contributing policy is clear/useful?

Status update

---

content/presubmission_inquiry.md

Emphasize "we" over "I". Other minor edits and add letter header.

Minor edits to presubmission_inquiry.md

---

rules.md

I think we should dedicate a section to talk about model security, specifically within the context of biology.

Add section on model security

---

content/presubmission_inquiry.md

The first paragraph was a little wordy/awkward, so I tried to cut it down some. Feel free to make any recommendations/changes. I also tried to fix some of the places that seemed a little repetitive. The general flow probably still needs a little work.

Minor changes to presubmission_inquiry.md 

---

content/12.privacy.md

No period for rule ten

---

contributors.md

Please add me to the list :smile:

Update contributors.md: add Michael M. Hoffman

---

contributors.md

Thanks for the comment @akundaje!

Include Anshul Kundaje

---

rules.md

I split rule 2 into two subcategories. They seem to be related, but there are two aspects to it. 
- One is to see whether traditional ML already solves the problem. 
- The other is to use a baseline model like (multinomial) logistic regression (ideally implemented in the same software framework that is then later used for implementing the DNN, in order to check if there are any issues with the DNN implementation and use it as a performance baseline. Ideally, the same normalization steps and optimization algorithms should be used to assess whether potential problems are introduced when the DNN is implemented.

Further organize rule 2

---

content/12.privacy.md

Semicolons for multiple citations

---

content/12.privacy.md

Fixing a typo

---

contributors.md

- [x ] Yes, I added myself or am already a contributor

chevrette drafting

---

content/12.privacy.md

As this rule is particularly important, I strengthened the warnings within the rule to really drive the point home, as well as made it clear that the rule doesn't just apply to medical data.

Strengthen the warnings provided in rule 10

---

content/03.ml-concepts.md

This is an initial draft of Rule 1. I have mostly focused on a high level discussion of biased data and validating models (since that is what's mentioned in `rules.md`). I am hoping that this will initiate discussion of this rule, since we will inevitably need to heavily pare down general ML advice to find the subset that is most relevant or critical for a broad range of DL applications in computational biology.

Initial draft of Rule 1: Deep learning is still machine learning

---

content/08.hyperparameters.md
content/citation-tags.tsv
contributors.md

I wanted to get some text down on this rule so that the blank page effect becomes less intimidating. I'm expecting this will need some substantial revision and re-working (especially with regards to rule 2 once a draft of that lands).

Initial draft of text for Rule #6 (Hyperparameter optimization)

---

content/02.intro.md
content/03.ml-concepts.md
content/04.baselines.md
content/05.dl-complexities.md
content/06.know-your-problem.md
content/07.architecture-and-representation.md
content/08.hyperparameters.md
content/09.overfitting.md
content/10.blackbox.md
content/11.interpretation.md
content/12.privacy.md
content/13.conclusion.md

For easier linking within the manuscript. See https://github.com/Benjamin-Lee/deep-rules/pull/90#discussion_r242376812.

Add anchors

---

README.md

Get rid of outdated sentence in the README

---

content/04.baselines.md

Adding mention of the existence of recent hybrid models (combining DL and KNN) and their utility.

Add hybrid model concept

---

content/03.ml-concepts.md

Added a bio-focused citation for AUROC problems on imbalanced datasets that might be useful for readers.
Very minor caveat addition and grammar modification.

Reference and minor edit to ML-concepts

---

CONTRIBUTING.md
content/00.front-matter.md
content/metadata.yaml

Add additional information about authorship metadata

---

content/09.overfitting.md
content/citation-tags.tsv

Closes #126.  I switched one URL to a tag, the other to the JMLR URL.

Correct broken URL citations

---

content/06.know-your-problem.md
content/metadata.yaml

This can probably be tweaked a bit to have some better flow, but I think right now just getting more words on to paper/screen is important and we can revise/cut later on.

Small tip 4 additions and clarifications.

---

content/metadata.yaml

Added my information to `content/metadata.yaml`.

Updated author info

---

content/metadata.yaml

Add author info rasbt

---

content/manual-references.json

This adds a manual override for one of the new citations in #124.

Manual NVIDIA cuDNN reference

---

content/03.ml-concepts.md

Just add #20 more explicitly to general ML concepts to close this issue.
Fixes #20

Add explicit coverage of test-set locking (#20) to ml-concepts tip.

---

content/11.interpretation.md

Add some language to improve the flow

---

content/11.interpretation.md

This PR includes small edits to Tip 9 intended to make discussion of prediction vs understanding more explicit, as suggested in #37.
It also might be worth considering changing the tip title to a positive phrasing. I'm not sure how to do so while maintaining distinction between Tips 9 and 8.

Minor edits to Tip 9

---

content/metadata.yaml
contributors.md

Adding author info, as requested in #144.

Update blengerich author info

---

contributors.md

Very small update. I added `Yes` to my entry in the accountability column of `contributors.md`.

Updated accountability in contributors.md

---

content/metadata.yaml
contributors.md

Add agitter author information

---

content/12.privacy.md

Add citation about Ten simple rules for responsible big data research. 

---

content/05.dl-complexities.md

Some more citations and fixes to complexities tip

---

content/metadata.yaml

- [ X] Yes, I added myself or am already a contributor

Added SiminaB information to metadata.yaml

---

contributors.md

- [ X] Yes, I added myself or am already a contributor

Added self as accountable in contributors.md

---

content/04.baselines.md

Some tweaks to baselines/tip 2. Get rid of informal language in first sentence

---

content/12.privacy.md

In addressing #159 it felt like more work needed to be done to hone this section. I now joined the discussion of the risks, with existing but not-yet-practical-to-widely-apply potential solutions. I think this framing makes it easier to get the important bits out of the paragraph.

Refine Tip 10 (Privacy)

---

content/13.conclusion.md

Conclusion first draft

---

content/citation-tags.tsv

Remove duplicate tag

---

contributors.md

- [x ] Yes, I added myself or am already a contributor

Added myself to contributors.md

---

content/metadata.yaml
contributors.md

Will need to edit final draft for this to be strictly true, which is the intent; recent remark about LR vs. DL (or, for that matter, RF/similar ML) is worth emphasizing.  If the training data is insufficiently informative, or lacks structure, the marginal benefit of DL relative to the marginal effort involved training DNN/CNN type models is usually difficult to justify.
- [ x ] Yes, I added myself or am already a contributor
Per issue, I have indicated my accountability for what I contribute to the paper.

indicate accountability

---

content/03.ml-concepts.md
content/04.baselines.md
content/05.dl-complexities.md
content/06.know-your-problem.md
content/07.architecture-and-representation.md
content/08.hyperparameters.md
content/09.overfitting.md
content/11.interpretation.md
content/12.privacy.md

In response to https://github.com/Benjamin-Lee/deep-rules/issues/174#issuecomment-484719672.

Add action points

---

content/metadata.yaml

mc affiliation update

---

content/09.overfitting.md

Update bibliography for 1807.00431

---

content/04.baselines.md

Study was published in the PSB Proceedings:
https://www.ncbi.nlm.nih.gov/pmc/articles/PMC6417816/
https://www.ncbi.nlm.nih.gov/pubmed/30963075
https://doi.org/10.1142/9789813279827_0033

Update "Continental Breakfast Included" citation

---

content/03.ml-concepts.md
content/04.baselines.md
content/06.know-your-problem.md
content/08.hyperparameters.md
content/12.privacy.md

Just a few nitpicks upon a fresh reread of the paper

---

content/10.blackbox.md
content/11.interpretation.md
content/manual-references.json

This PR is a rewrite of the blackbox rule at a higher level with references to recent and updated literature.

Black box rule rewrite (close #209)

---

content/09.overfitting.md

This PR closes #202 by specifically mentioning the dangers of splitting sequence data.

Close #202

---

content/03.ml-concepts.md
content/06.know-your-problem.md
content/metadata.yaml

- [ x] Yes, I added myself or am already a contributor

editing to point 1

---

content/04.baselines.md

This closes #187, which I think is a good point to include.

Add a mention of testing non-ML tools as a baseline

---

content/06.know-your-problem.md

This PR extends from the discussion in https://github.com/Benjamin-Lee/deep-rules/pull/218.
I have added some additional text about how simulation methods can be used to help you understand your data, in order to help tie this paragraph to the central idea of this section `knowing your data/problem`.
@pstew @cgreene Please let me know if these edits make sense, if I misunderstood something as I know I'm new to contributing to this manuscript.

Update simulation text for section 06

---

content/12.privacy.md

We had this language in an older version but it was since dropped (possibly unintentionally). I think we should add it back in.

Add examples of private bio/biomed data (closes #188)

---

contributors.md

Fix Elana Fertig contributions

---

content/metadata.yaml
contributors.md

This PR is just adding my name to the list of contributors

Add Alexandra Lee to list of contributors

---

content/03.ml-concepts.md

This PR is wordsmithing the text to the ML section to help with flow. Please feel free to take or leave any changes  in case I may have misunderstood the original authors intent.

Wordsmith ML text

---

content/cover_letter.md

I'd appreciate some help in drafting the cover letter from some of the more senior authors. I've done it myself a few times, though only once for a Ten Simple Rules article.

Add cover letter

---

content/cover_letter.md

Add @siminab suggestions to the cover letter

---

content/presubmission_inquiry_nature_comput_sci.md

As first raised in #270, this letter seeks to gauge their interest in parallel with our work to finish up the manuscript.

Presubmission inquiry to Nature Computational Science

---

content/02.intro.md

As promised, I started revisiting the chapters that we have. Originally, I planned to go through the whole article (or at least more of the chapters) today, but it's a super busy semester, and I found the intro a bit rough so that I probably spent too much time on it. 
I made a few changes while trying to preserve the original text as much as possible. However, I felt like some sentences needed to be rephrased. Let me know what you think.

feedback on 02 intro

---

content/09.overfitting.md
content/12.privacy.md

Tip 10 tweaks

---

content/09.overfitting.md

Rewordings and adding a citation.

Tip 7 Tweaks

---

content/12.privacy.md
content/13.conclusion.md

Some minor language fixes and rewording (I thought the last sentence sounded a bit weird)

Conclusion Tweaks

---

content/08.hyperparameters.md

Minor additions (loss function as hyperparam choice) and some typo fixes.

Tip 6 Tweaks

---

content/05.dl-complexities.md

This tip is pretty succinct and spot on. I don't have any major suggestions besides some minor tweaks.

Tip 3 Tweaks

---

content/11.interpretation.md

Mainly only some formatting fixes and rewordings.

Tip 9 Tweaks

---

content/10.blackbox.md

Mostly some additional references.

Tip-8 Tweaks

---

content/08.hyperparameters.md
content/10.blackbox.md

Reading through the manuscript it looks great! Found 2 citations that weren't recognized and so tried to fix these (though I'm not sure if the fixes worked because I wasn't sure how to see the updated compiled manuscript). I also made one minor text edit.

Minor text edit and tried to fix citation tags

---

content/13.conclusion.md

This is just adding some initial text for the new ethics section, while waiting for @juancarmona to be available.

Add start of ethics section

---

content/09.overfitting.md

Close #302 (missing citation)

---

content/05.dl-complexities.md
content/06.know-your-problem.md

I'm not going to waste the valuable time of the contributors with a review for this. If anyone sees a problem, let me know.

Close #300

---

content/12.privacy.md

Close #304 (ethics revisions)

---

content/02.intro.md

This section probably predates the publication of the paper but deserves a citation

Add Manubot citation

---

content/metadata.yaml

Adding more author data as per discussion in #226

Adding rasbt author metadata

---

content/metadata.yaml

Updating affiliation and funder info.

add funding info / new affiliation

---

content/metadata.yaml

Updated author info/affiliation

---

content/metadata.yaml

Updated my funding information and affiliation.

Added funding info and updated affiliation

---

content/metadata.yaml

Update agitter metadata

---

content/metadata.yaml

Adding the newly requested metadata

add casey metadata

---

content/metadata.yaml

- [x ] Yes, I added myself or am already a contributor

Added COI, funding info for Simina Boca

---

content/metadata.yaml

Add postcode, approval, and accountability.

Update finlaymaguire metadata

---

content/04.baselines.md
content/metadata.yaml

Did a final read through of the manuscript and it all looks great! This PR has one minor text change to tip 2 and I updated my metadata information
I've learned so much from this experience. Thank you for giving me the opportunity to contribute, very excited to see this work shared!

Update Alexandra's metadata and minor text change

---

content/metadata.yaml

Add zipcode metadata required for submission

---

content/metadata.yaml

- [x ] Yes, I added myself or am already a contributor

Added postcode, approval, accountability for Simina Boca

---

contributors.md

Add Michael Kessler to contributors.md

---

content/metadata.yaml
contributors.md

The PR updates my info in the metadata

Tbrittoborges patch 1

---

content/metadata.yaml

Update BDL metadata

---

content/metadata.yaml

- [ x] Yes, I added myself or am already a contributor
Final approval information

Final approval A Titus

---

content/metadata.yaml

Updated affiliations; added conflicts, postcode, approval, accountability

update AKK metadata

---

content/metadata.yaml

Update metadata.yaml with pstew info/approval

---

content/metadata.yaml

JJC metadata included

---

content/metadata.yaml

Updated my metadata to include the new fields required for submission.

Added approval and further info 

---

content/metadata.yaml

updated metadata for beth signal

---

content/metadata.yaml

Added conflict and funding to metadata. So sorry to be so late. I thought I had updated this already. Thank you for pinging me

Update metadata for Alexandra Lee

---

content/metadata.yaml

meta yaml update

---

content/metadata.yaml

- [ x ] Yes, I added myself or am already a contributor
Update accountability, affiliations, approval, and funding sections.

Update funding, approval, accountability

---

content/14.acknowledgements.md

Add list of collaborators who agreed to be acknowledged

---

content/metadata.yaml

Based on the [list as of the manuscript freeze date](https://github.com/Benjamin-Lee/deep-rules/graphs/contributors?from=2016-07-31&to=2021-01-28&type=c) of 2021-01-28.

Finalize author order for submission

---

content/00.front-matter.md
content/14.acknowledgements.md
content/metadata.yaml

This is a work in progress.  I'll need to check the artifacts to make sure the table renders correctly and will request a review when it works.
Derived from https://github.com/greenelab/covid19-review/blob/master/content/70.coi-contribs.md

Add competing interests table and statement

---

content/03.when-to-use-dl.md
content/response.md

address reviewer 1  concern re dataset sizes

---

content/04.baselines.md

Saw a study that supports one of our claims re ML baselines and added it

added study supporting ML as baseline

---

content/response.md

Add opening and closing to response letter

---

content/metadata.yaml
contributors.md

Still the same person, just changed my first name. ORCID is still the same.

updated name
